language: java

jdk:
  - oraclejdk8
  
branches:
  only:
    - master
    - develop
    
notifications:
  email:
    recipients:
      - tamara.jimenez.diaz@alumnos.upm.es

script: mvn verify